language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - MODULE_NAME="controller_annotations"
    - DRUSH_VERSION="^9.4"
    - CODER_VERSION="^8.2"
  matrix:
    - DRUPAL_VERSION="8.2"
    - DRUPAL_VERSION="8.3"
    - DRUPAL_VERSION="8.4"
    - DRUPAL_VERSION="8.5"
    - DRUPAL_VERSION="8.6"
    - DRUPAL_VERSION="8.7"

matrix:
  fast_finish: true
  allow_failures:
    - env: DRUPAL_VERSION="8.7.x"
  exclude:
    - php: 7.2
      env: DRUPAL_VERSION="8.2.x"
    - php: 7.2
      env: DRUPAL_VERSION="8.3.x"
    - php: 7.2
      env: DRUPAL_VERSION="8.4.x"

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  # Decide if we are going to do a full inspection on this build
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ] && [ "$DRUPAL_VERSION" == "8.5.x" ] ; then export INSPECT="true"; else export INSPECT="false"; fi;
  # Decide if this build is used to push upstream changes to Drupal.org
  - if [ "$INSPECT" == "true" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then export UPSTREAM="true"; else export UPSTREAM="false"; fi;

  # Disable xdebug when we do not generate coverage files
  - if [ "$INSPECT" == "false" ]; then phpenv config-rm xdebug.ini; fi;

  # Composer
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc
  - composer self-update

  # Load global dependencies
  - composer global require drush/drush:$DRUSH_VERSION
  - composer global require drupal/coder:$CODER_VERSION
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - phpcs --config-set installed_paths ~/.composer/vendor/drupal/coder/coder_sniffer

  # Ensure the PHP environment is ready
  - phpenv rehash

  # Isolate our module into a separate directory
  - mkdir module
  - shopt -s extglob dotglob
  - mv !(module) module
  - shopt -u dotglob

  # Install with composer
  - composer create-project drupal-composer/drupal-project:$DRUPAL_VERSION-dev drupal --stability dev --no-interaction

  # Make sure Drupal can access our module by using a symlink
  - ln -s $PWD/module drupal/modules/$MODULE_NAME
  - cd drupal
